[build]
  base = "web"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"

# Handle 404 errors with custom page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
