ALTER TABLE public.users
ADD COLUMN full_name TEXT NULL,
ADD COLUMN avatar_url TEXT NULL,
ADD COLUMN phone TEXT NULL,
ADD COLUMN language TEXT NULL DEFAULT 'English',
ADD COLUMN currency TEXT NULL DEFAULT 'TZS',
ADD COLUMN email_notifications BOOLEAN NULL DEFAULT TRUE,
ADD COLUMN push_notifications BOOLEAN NULL DEFAULT TRUE,
ADD COLUMN sms_notifications BOOLEAN NULL DEFAULT FALSE,
ADD COLUMN theme TEXT NULL DEFAULT 'system';
